{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-poilog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poilog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poilog/poilog_{{ version }}.tar.gz
  sha256: b126416e50d87c758fc058d05c6c4c9fd74fa1a6850da66acc7faf50c415389f

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('poilog')"           # [not win]
    - "\"%R%\" -e \"library('poilog')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=poilog
  license: GPL-3.0-only
  summary: Functions for obtaining the density, random deviates  and maximum likelihood estimates of the Poisson lognormal  distribution and the bivariate Poisson lognormal distribution.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
