# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vtuRd7/J9BvQAAtesXnC0/0y48d8iVHHz2uB2q1PpjOCUlSsfB3iQo8csOD9Dy32FFFwQr3wjK+E3tauLVvSrvoxc6Qlz//KSRF5bLY1PrtxzomuwjbIU3TBLwqU3+jseTEaRx10iFW28YF6oiGnwiboWk4IgNCdngJSczA3+L3K1U+E/c92h3rJC+Hqy++cnzv6RLWxLoFdMrSt+dNPeHv8plsXteMs1tsGagD85pQx9yLIJe2E12Jv4LwsBLud+510vaNBZZ/fJZs1TvjL7madPKmPv0j6zsJapmxFix07N9NtsaSuJfrykYyqhcp6uDspH6QFS868YmZCV1+Zejark2NSUo1wpw9cICyALUYyme/hfAmn8Ni6czsyPZ40opOti1PSsLfUSO6MaWnZDwH1gfvF/C6VH+NicuVpC8GZUERu04oU3V1ev+iqMlHp6ALKn1zlZWnY4yNsFdWqV98N+Jo9EaiJMcnlYbbx32rtUU8iu5Fh6vhoTC4VYpeIV4FlFvPW9RkmBKfWqgsaEQ+qvkAIQUJk9T3KVA1zy31AfQnOLFV/k07cmhzSs6iY4hoXMrUK89hvpbDD/9RODcALrYjAQb+00mKz7I4BmpAmW3ndEfe9pcWhFknLVkhis8Dd6uIqSFzmquF14EOYt14DN1wnBVUddRmQwlMrhK8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
