travis:
  secure:
    BINSTAR_TOKEN: Vb4QnMyRWk/3K5ZbBHgmwimcSuBgod3vwPHnM+82UIK3La3Oo5ppDGbSYJiEF35bIaVrdmU0EGbSR9zY3q0HrOzTqeLcOYOtu74r4j3vRNhTsuKPNaQ24ItqgxIvieVkat17i5Rn0TdjsmEgDYbqXOXNgLg3k8/KmoBpLPudhBWCGbBp7X5VGh4mZYvSeoHklM+6neyWakUwdJhXpeiKdMHuTzzFEJ+J3d6E5kBtg71M2pjYG41eAw7O4RqxUfmK+ddhklAoVBBgcvGtY5HIEvcXdZDxCfpQrDb8FZWNVPsVwANSXfGM2g2WFVyBUi7CF+FDzDm/ilLL6OQPjm4m8D6gphKJV9C3wU8df72DhPzInSSXFt1iIVTKHLu7kwRRzi+hpUbZ02CnRuwMS9GLlEXqbsFlsDpGumbw3BldYfFp/BYgxNSOKEgxOXBDFH5aTpo2L4p2OFUXS0cXMJkQHDuqM0OuZomxoAC1MO4NAInbEJqufrR1PM/syxOaO0lt3R+JdaOgCDNatcKCR/1yd6GCIYm7kzSQTUm99mzxjTMdSQ2sUf8zU5ka5/uYL9Z2fQHSkpilPGPgVQHJHXtHHStLGaIJZyLV7l3+cq/c0WT3ro1DQgCWlLYWxnGuitwg88cAcs2T65EeUr0n5UbwuQeKvPoB3HJNVfzATCMtDZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
