appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: vtuRd7/J9BvQAAtesXnC0/0y48d8iVHHz2uB2q1PpjOCUlSsfB3iQo8csOD9Dy32FFFwQr3wjK+E3tauLVvSrvoxc6Qlz//KSRF5bLY1PrtxzomuwjbIU3TBLwqU3+jseTEaRx10iFW28YF6oiGnwiboWk4IgNCdngJSczA3+L3K1U+E/c92h3rJC+Hqy++cnzv6RLWxLoFdMrSt+dNPeHv8plsXteMs1tsGagD85pQx9yLIJe2E12Jv4LwsBLud+510vaNBZZ/fJZs1TvjL7madPKmPv0j6zsJapmxFix07N9NtsaSuJfrykYyqhcp6uDspH6QFS868YmZCV1+Zejark2NSUo1wpw9cICyALUYyme/hfAmn8Ni6czsyPZ40opOti1PSsLfUSO6MaWnZDwH1gfvF/C6VH+NicuVpC8GZUERu04oU3V1ev+iqMlHp6ALKn1zlZWnY4yNsFdWqV98N+Jo9EaiJMcnlYbbx32rtUU8iu5Fh6vhoTC4VYpeIV4FlFvPW9RkmBKfWqgsaEQ+qvkAIQUJk9T3KVA1zy31AfQnOLFV/k07cmhzSs6iY4hoXMrUK89hvpbDD/9RODcALrYjAQb+00mKz7I4BmpAmW3ndEfe9pcWhFknLVkhis8Dd6uIqSFzmquF14EOYt14DN1wnBVUddRmQwlMrhK8=
